export default [
  { index: null, pvisible: false, pname: '全部分区', category: [] },
  { index: null, pvisible: false, pname: '动画', category: ["MAD·AMV", "MMD·3D", "短片·手书·配音", "手办·模玩", "特摄", "综合"] },
  { index: null, pvisible: false, pname: '番剧', category: ["完结动画", "连载动画", "资讯", "官方延伸"] },
  { index: null, pvisible: false, pname: '国创', category: ["国产动画", "国产原创相关", "布袋戏", "动态漫·广播剧", "资讯"] },
  { index: null, pvisible: false, pname: '音乐', category: ["原创音乐", "翻唱", "VOCALOID·UTAU", "电音", "演奏", "MV", "音乐现场", "音乐综合"] },
  { index: null, pvisible: false, pname: '舞蹈', category: ["宅舞", "街舞", "明星舞蹈", "中国舞", "舞蹈综合", "舞蹈教程"] },
  { index: null, pvisible: false, pname: '游戏', category: ["单机游戏", "电子竞技", "手机游戏", "网络游戏", "桌游棋牌", "GMV", "音游", "Mugen"] },
  { index: null, pvisible: false, pname: '知识', category: ["科学科普", "社科人文", "财经", "校园学习", "职业职场", "野生技术协会"] },
  { index: null, pvisible: false, pname: '数码', category: ["手机平板", "电脑装机", "摄影摄像", "影音智能"] },
  { index: null, pvisible: false, pname: '汽车', category: ["汽车生活", "汽车文化", "汽车极客", "智能出行", "购车攻略"] },
  { index: null, pvisible: false, pname: '生活', category: ["搞笑", "日常", "动物圈", "手工", "绘画", "运动", "其他"] },
  { index: null, pvisible: false, pname: '美食', category: ["美食制作", "美食侦探", "美食测评", "田园美食", "美食记录"] },
  { index: null, pvisible: false, pname: '动物圈', category: ["喵星人", "汪星人", "大熊猫", "野生动物", "爬宠", "动物综合"] },
  { index: null, pvisible: false, pname: '鬼畜', category: ["鬼畜调教", "音MAD", "人力VOCALOID", "鬼畜剧场", "教程演示"] },
  { index: null, pvisible: false, pname: '时尚', category: ["美妆", "服饰", "健身", "T台", "风尚标"] },
  { index: null, pvisible: false, pname: '资讯', category: ["热点", "环球", "社会", "综合"] },
  { index: null, pvisible: false, pname: '娱乐', category: ["综艺", "明星"] },
  { index: null, pvisible: false, pname: '影视', category: ["影视杂谈", "影视剪辑", "短片", "预告·资讯"] },
  { index: null, pvisible: false, pname: '纪录片', category: ["人文·历史", "科学·探索·自然", "军事", "社会·美食·旅行"] },
  { index: null, pvisible: false, pname: '电影', category: ["国产电影", "欧美电影", "日本电影", "其他国家"] },
  { index: null, pvisible: false, pname: '电视剧', category: ["国产剧", "海外剧"] },
]